name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: cr1m1/waka-readme@latest
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
